# Project information
site_name: BO Wiki
site_url: https://bo.lyccrius.site
site_author: Lyccrius
site_description: Lyccrius's BO Wiki

# Repository
repo_name: 'lyccrius/bo'
repo_url: 'https://github.com/lyccrius/bo'

# Copyright
copyright: 'Copyright &copy; 2023 - 2023 Lyccrius'

# Configuration
theme:
  name: material
  language: 'zh'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  favicon: 'favicon.png'
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
  icon:
    logo: 'material/school-outline'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Customization
extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

# Page tree
nav:
  - 首页:
    - index.md
    - 书单: list.md
  - 细胞生物学:
    - cell-biology/index.md
    - 细胞的结构和功能: cell-biology/cell-structure-and-function.md
    - 化学成分: cell-biology/chemical-composition.md
    - 细胞器: cell-biology/organelle.md
    - 细胞代谢: cell-biology/cell-metabolism.md
    - 蛋白质合成: cell-biology/protein-synthesis.md
    - 通过膜的转运: cell-biology/membrane-transport.md
    - 有丝分裂和减数分裂: cell-biology/mitosis-and-meiosis.md
    - 微生物学: cell-biology/microbiology.md
    - 生物工程学: cell-biology/bioengineering.md
  - 植物解剖和生理: 
    - plant-anatomy-and-physiology/index.md
    - 组织和器官的结构和功能: plant-anatomy-and-physiology/tissue-and-organ-structure-function.md
    - 光合作用: plant-anatomy-and-physiology/photosynthesis.md
    - 蒸腾作用: plant-anatomy-and-physiology/transpiration.md
    - 气体交换: plant-anatomy-and-physiology/gas-exchange.md
    - 水分、矿物质和同化物的运输: plant-anatomy-and-physiology/transport.md
    - 生长和发育: plant-anatomy-and-physiology/growth-and-development.md
    - 生殖: plant-anatomy-and-physiology/reproduction.md
  - 动物解剖和生理:
    - animals-anatomy-and-physiology/index.md
    - 组织和器官的结构和功能: animals-anatomy-and-physiology/tissue-and-organ-structure-function.md
    - 消化和营养: animals-anatomy-and-physiology/digestion-and-nutrition.md
    - 呼吸作用: animals-anatomy-and-physiology/cellular-respiration.md
    - 血液循环: animals-anatomy-and-physiology/blood-circulation.md
    - 排泄调节: animals-anatomy-and-physiology/excretion-regulation.md
    - 生殖和发育: animals-anatomy-and-physiology/reproduction-and-development.md
    - 免疫: animals-anatomy-and-physiology/immunity.md
    - 皮肤及其衍生物: animals-anatomy-and-physiology/skin-and-its-derivative.md
    - 运动器官: animals-anatomy-and-physiology/locomotive-organ.md
  - 动物行为学:
    - ethology/index.md
  - 遗传学与进化:
    - genetics-and-evolution/index.md
    - 变异：突变和渐变: genetics-and-evolution/mutation.md
    - 孟德尔遗传: genetics-and-evolution/mendelian-inheritance.md
    - 多等位性: genetics-and-evolution/multi-allelic.md
    - 重组: genetics-and-evolution/recombination.md
    - 伴性遗传: genetics-and-evolution/sex-linked-inheritance.md
    - 哈迪-温博格定律: genetics-and-evolution/hardy-weinberg-principle.md
    - 演化的机理: genetics-and-evolution/evolution-mechanism.md
  - 生态学:
    - ecology/index.md
  - 生物系统学:
    - biosystematics/index.md